import { Match, TeamStanding } from "./types";

export const ipl2025Teams = [
  {
    id: "csk",
    name: "Chennai Super Kings",
    shortName: "CSK",
    primaryColor: "#FFFF3C",
    secondaryColor: "#0081E9",
    logo: "/csk.svg?height=48&width=48",
  },
  {
    id: "mi",
    name: "Mumbai Indians",
    shortName: "MI",
    primaryColor: "#004BA0",
    secondaryColor: "#D1AB3E",
    logo: "/mi.svg?height=48&width=48",
  },
  {
    id: "rcb",
    name: "Royal Challengers Bengaluru",
    shortName: "RCB",
    primaryColor: "#EC1C24",
    secondaryColor: "#000000",
    logo: "/rcb.svg?height=48&width=48",
  },
  {
    id: "dc",
    name: "Delhi Capitals",
    shortName: "DC",
    primaryColor: "#0078BC",
    secondaryColor: "#EF1C25",
    logo: "/dc.svg?height=48&width=48",
  },
  {
    id: "kkr",
    name: "Kolkata Knight Riders",
    shortName: "KKR",
    primaryColor: "#3A225D",
    secondaryColor: "#B3A123",
    logo: "/kkr.svg?height=48&width=48",
  },
  {
    id: "pbks",
    name: "Punjab Kings",
    shortName: "PBKS",
    primaryColor: "#ED1B24",
    secondaryColor: "#A7A9AC",
    logo: "/pbks.svg?height=48&width=48",
  },
  {
    id: "rr",
    name: "Rajasthan Royals",
    shortName: "RR",
    primaryColor: "#EA1A85",
    secondaryColor: "#254AA5",
    logo: "/rr.svg?height=48&width=48",
  },
  {
    id: "srh",
    name: "Sunrisers Hyderabad",
    shortName: "SRH",
    primaryColor: "#F7A721",
    secondaryColor: "#E95E0B",
    logo: "/srh.svg?height=48&width=48",
  },
  {
    id: "gt",
    name: "Gujarat Titans",
    shortName: "GT",
    primaryColor: "#1C2C5B",
    secondaryColor: "#0B4973",
    logo: "/gt.svg?height=48&width=48",
  },
  {
    id: "lsg",
    name: "Lucknow Super Giants",
    shortName: "LSG",
    primaryColor: "#A72056",
    secondaryColor: "#FFCC00",
    logo: "/lsg.svg?height=48&width=48",
  },
];

export const ipl2025Fixtures: Match[] = [
  {
    id: "kkr-rcb-1",
    matchNumber: 1,
    team1: "kkr",
    team2: "rcb",
    isCompleted: true,
    winner: "rcb",
  },
  {
    id: "srh-rr-2",
    matchNumber: 2,
    team1: "srh",
    team2: "rr",
    isCompleted: true,
    winner: "srh",
  },
  {
    id: "mi-csk-3",
    matchNumber: 3,
    team1: "mi",
    team2: "csk",
    isCompleted: true,
    winner: "csk",
  },
  {
    id: "lsg-dc-4",
    matchNumber: 4,
    team1: "lsg",
    team2: "dc",
    isCompleted: true,
    winner: "dc",
  },
  {
    id: "pbks-gt-5",
    matchNumber: 5,
    team1: "pbks",
    team2: "gt",
    isCompleted: true,
    winner: "pbks",
  },
  {
    id: "rr-kkr-6",
    matchNumber: 6,
    team1: "rr",
    team2: "kkr",
    isCompleted: true,
    winner: "kkr",
  },
  {
    id: "srh-lsg-7",
    matchNumber: 7,
    team1: "srh",
    team2: "lsg",
    isCompleted: true,
    winner: "lsg",
  },
  {
    id: "rcb-csk-8",
    matchNumber: 8,
    team1: "rcb",
    team2: "csk",
    isCompleted: true,
    winner: "rcb",
  },
  {
    id: "gt-mi-9",
    matchNumber: 9,
    team1: "gt",
    team2: "mi",
    isCompleted: true,
    winner: "gt",
  },
  {
    id: "srh-dc-10",
    matchNumber: 10,
    team1: "srh",
    team2: "dc",
    isCompleted: true,
    winner: "dc",
  },
  {
    id: "rr-csk-11",
    matchNumber: 11,
    team1: "rr",
    team2: "csk",
    isCompleted: true,
    winner: "rr",
  },
  {
    id: "kkr-mi-12",
    matchNumber: 12,
    team1: "kkr",
    team2: "mi",
    isCompleted: true,
    winner: "mi",
  },
  {
    id: "lsg-pbks-13",
    matchNumber: 13,
    team1: "lsg",
    team2: "pbks",
    isCompleted: true,
    winner: "pbks",
  },
  {
    id: "rcb-gt-14",
    matchNumber: 14,
    team1: "rcb",
    team2: "gt",
    isCompleted: true,
    winner: "gt",
  },
  {
    id: "kkr-srh-15",
    matchNumber: 15,
    team1: "kkr",
    team2: "srh",
    isCompleted: true,
    winner: "kkr",
  },
  {
    id: "lsg-mi-16",
    matchNumber: 16,
    team1: "lsg",
    team2: "mi",
    isCompleted: true,
    winner: "lsg",
  },
  {
    id: "dc-csk-17",
    matchNumber: 17,
    team1: "dc",
    team2: "csk",
    isCompleted: true,
    winner: "dc",
  },
  {
    id: "pbks-rr-18",
    matchNumber: 18,
    team1: "pbks",
    team2: "rr",
    isCompleted: true,
    winner: "rr",
  },
  {
    id: "srh-gt-19",
    matchNumber: 19,
    team1: "srh",
    team2: "gt",
    isCompleted: true,
    winner: "gt",
  },
  {
    id: "rcb-mi-20",
    matchNumber: 20,
    team1: "rcb",
    team2: "mi",
    isCompleted: true,
    winner: "rcb",
  },
  {
    id: "lsg-kkr-21",
    matchNumber: 21,
    team1: "lsg",
    team2: "kkr",
    isCompleted: true,
    winner: "lsg",
  },
  {
    id: "pbks-csk-22",
    matchNumber: 22,
    team1: "pbks",
    team2: "csk",
    isCompleted: true,
    winner: "pbks",
  },
  {
    id: "gt-rr-23",
    matchNumber: 23,
    team1: "gt",
    team2: "rr",
    isCompleted: true,
    winner: "gt",
  },
  {
    id: "dc-rcb-24",
    matchNumber: 24,
    team1: "dc",
    team2: "rcb",
    isCompleted: true,
    winner: "dc",
  },
  {
    id: "csk-kkr-25",
    matchNumber: 25,
    team1: "csk",
    team2: "kkr",
    isCompleted: true,
    winner: "kkr",
  },
  {
    id: "gt-lsg-26",
    matchNumber: 26,
    team1: "gt",
    team2: "lsg",
    isCompleted: true,
    winner: "lsg",
  },
  {
    id: "pbks-srh-27",
    matchNumber: 27,
    team1: "pbks",
    team2: "srh",
    isCompleted: true,
    winner: "srh",
  },
  {
    id: "rr-rcb-28",
    matchNumber: 28,
    team1: "rr",
    team2: "rcb",
    isCompleted: true,
    winner: "rcb",
  },
  {
    id: "mi-dc-29",
    matchNumber: 29,
    team1: "mi",
    team2: "dc",
    isCompleted: true,
    winner: "mi",
  },
  {
    id: "lsg-csk-30",
    matchNumber: 30,
    team1: "lsg",
    team2: "csk",
    isCompleted: true,
    winner: "csk",
  },
  {
    id: "pbks-kkr-31",
    matchNumber: 31,
    team1: "pbks",
    team2: "kkr",
    isCompleted: true,
    winner: "pbks",
  },
  {
    id: "dc-rr-32",
    matchNumber: 32,
    team1: "dc",
    team2: "rr",
    isCompleted: true,
    winner: "dc",
  },
  {
    id: "mi-srh-33",
    matchNumber: 33,
    team1: "mi",
    team2: "srh",
    isCompleted: true,
    winner: "mi",
  },
  {
    id: "rcb-pbks-34",
    matchNumber: 34,
    team1: "rcb",
    team2: "pbks",
    isCompleted: true,
    winner: "pbks",
  },
  {
    id: "gt-dc-35",
    matchNumber: 35,
    team1: "gt",
    team2: "dc",
    isCompleted: true,
    winner: "gt",
  },
  {
    id: "rr-lsg-36",
    matchNumber: 36,
    team1: "rr",
    team2: "lsg",
    isCompleted: true,
    winner: "lsg",
  },
  {
    id: "pbks-rcb-37",
    matchNumber: 37,
    team1: "pbks",
    team2: "rcb",
    isCompleted: true,
    winner: "rcb",
  },
  {
    id: "mi-csk-38",
    matchNumber: 38,
    team1: "mi",
    team2: "csk",
    isCompleted: true,
    winner: "mi",
  },
  {
    id: "kkr-gt-39",
    matchNumber: 39,
    team1: "kkr",
    team2: "gt",
    isCompleted: true,
    winner: "gt",
  },
  {
    id: "lsg-dc-40",
    matchNumber: 40,
    team1: "lsg",
    team2: "dc",
    isCompleted: true,
    winner: "dc",
  },
  {
    id: "srh-mi-41",
    matchNumber: 41,
    team1: "srh",
    team2: "mi",
    isCompleted: true,
    winner: "mi",
  },
  {
    id: "rcb-rr-42",
    matchNumber: 42,
    team1: "rcb",
    team2: "rr",
    isCompleted: true,
    winner: "rcb",
  },
  {
    id: "csk-srh-43",
    matchNumber: 43,
    team1: "csk",
    team2: "srh",
    isCompleted: true,
    winner: "srh",
  },
  {
    id: "kkr-pbks-44",
    matchNumber: 44,
    team1: "kkr",
    team2: "pbks",
    isCompleted: false,
    winner: null,
  },
  {
    id: "mi-lsg-45",
    matchNumber: 45,
    team1: "mi",
    team2: "lsg",
    isCompleted: false,
    winner: null,
  },
  {
    id: "dc-rcb-46",
    matchNumber: 46,
    team1: "dc",
    team2: "rcb",
    isCompleted: false,
    winner: null,
  },
  {
    id: "rr-gt-47",
    matchNumber: 47,
    team1: "rr",
    team2: "gt",
    isCompleted: false,
    winner: null,
  },
  {
    id: "dc-kkr-48",
    matchNumber: 48,
    team1: "dc",
    team2: "kkr",
    isCompleted: false,
    winner: null,
  },
  {
    id: "csk-pbks-49",
    matchNumber: 49,
    team1: "csk",
    team2: "pbks",
    isCompleted: false,
    winner: null,
  },
  {
    id: "rr-mi-50",
    matchNumber: 50,
    team1: "rr",
    team2: "mi",
    isCompleted: false,
    winner: null,
  },
  {
    id: "gt-srh-51",
    matchNumber: 51,
    team1: "gt",
    team2: "srh",
    isCompleted: false,
    winner: null,
  },
  {
    id: "rcb-csk-52",
    matchNumber: 52,
    team1: "rcb",
    team2: "csk",
    isCompleted: false,
    winner: null,
  },
  {
    id: "kkr-rr-53",
    matchNumber: 53,
    team1: "kkr",
    team2: "rr",
    isCompleted: false,
    winner: null,
  },
  {
    id: "pbks-lsg-54",
    matchNumber: 54,
    team1: "pbks",
    team2: "lsg",
    isCompleted: false,
    winner: null,
  },
  {
    id: "srh-dc-55",
    matchNumber: 55,
    team1: "srh",
    team2: "dc",
    isCompleted: false,
    winner: null,
  },
  {
    id: "mi-gt-56",
    matchNumber: 56,
    team1: "mi",
    team2: "gt",
    isCompleted: false,
    winner: null,
  },
  {
    id: "kkr-csk-57",
    matchNumber: 57,
    team1: "kkr",
    team2: "csk",
    isCompleted: false,
    winner: null,
  },
  {
    id: "pbks-dc-58",
    matchNumber: 58,
    team1: "pbks",
    team2: "dc",
    isCompleted: false,
    winner: null,
  },
  {
    id: "lsg-rcb-59",
    matchNumber: 59,
    team1: "lsg",
    team2: "rcb",
    isCompleted: false,
    winner: null,
  },
  {
    id: "srh-kkr-60",
    matchNumber: 60,
    team1: "srh",
    team2: "kkr",
    isCompleted: false,
    winner: null,
  },
  {
    id: "pbks-mi-61",
    matchNumber: 61,
    team1: "pbks",
    team2: "mi",
    isCompleted: false,
    winner: null,
  },
  {
    id: "gt-dc-62",
    matchNumber: 62,
    team1: "gt",
    team2: "dc",
    isCompleted: false,
    winner: null,
  },
  {
    id: "rr-csk-63",
    matchNumber: 63,
    team1: "rr",
    team2: "csk",
    isCompleted: false,
    winner: null,
  },
  {
    id: "rcb-srh-64",
    matchNumber: 64,
    team1: "rcb",
    team2: "srh",
    isCompleted: false,
    winner: null,
  },
  {
    id: "gt-lsg-65",
    matchNumber: 65,
    team1: "gt",
    team2: "lsg",
    isCompleted: false,
    winner: null,
  },
  {
    id: "mi-dc-66",
    matchNumber: 66,
    team1: "mi",
    team2: "dc",
    isCompleted: false,
    winner: null,
  },
  {
    id: "rr-pbks-67",
    matchNumber: 67,
    team1: "rr",
    team2: "pbks",
    isCompleted: false,
    winner: null,
  },
  {
    id: "rcb-kkr-68",
    matchNumber: 68,
    team1: "rcb",
    team2: "kkr",
    isCompleted: false,
    winner: null,
  },
  {
    id: "gt-csk-69",
    matchNumber: 69,
    team1: "gt",
    team2: "csk",
    isCompleted: false,
    winner: null,
  },
  {
    id: "lsg-srh-70",
    matchNumber: 70,
    team1: "lsg",
    team2: "srh",
    isCompleted: false,
    winner: null,
  },
];

export const ipl2025PointsTable: TeamStanding[] = [
  {
    team: "Gujarat Titans",
    teamId: "gt",
    matches: 8,
    wins: 6,
    losses: 2,
    ties: 0,
    noResult: 0,
    points: 12,
    nrr: 1.104,
  },
  {
    team: "Delhi Capitals",
    teamId: "dc",
    matches: 8,
    wins: 6,
    losses: 2,
    ties: 0,
    noResult: 0,
    points: 12,
    nrr: 0.657,
  },
  {
    team: "Royal Challengers Bengaluru",
    teamId: "rcb",
    matches: 9,
    wins: 6,
    losses: 3,
    ties: 0,
    noResult: 0,
    points: 12,
    nrr: 0.482,
  },
  {
    team: "Mumbai Indians",
    teamId: "mi",
    matches: 9,
    wins: 5,
    losses: 4,
    ties: 0,
    noResult: 0,
    points: 10,
    nrr: 0.673,
  },
  {
    team: "Punjab Kings",
    teamId: "pbks",
    matches: 8,
    wins: 5,
    losses: 3,
    ties: 0,
    noResult: 0,
    points: 10,
    nrr: 0.177,
  },
  {
    team: "Lucknow Super Giants",
    teamId: "lsg",
    matches: 9,
    wins: 5,
    losses: 4,
    ties: 0,
    noResult: 0,
    points: 10,
    nrr: -0.054,
  },
  {
    team: "Kolkata Knight Riders",
    teamId: "kkr",
    matches: 8,
    wins: 3,
    losses: 5,
    ties: 0,
    noResult: 0,
    points: 6,
    nrr: 0.212,
  },
  {
    team: "Rajasthan Royals",
    teamId: "rr",
    matches: 9,
    wins: 2,
    losses: 7,
    ties: 0,
    noResult: 0,
    points: 4,
    nrr: -0.625,
  },
  {
    team: "Sunrisers Hyderabad",
    teamId: "srh",
    matches: 9,
    wins: 3,
    losses: 6,
    ties: 0,
    noResult: 0,
    points: 6,
    nrr: -1.103,
  },
  {
    team: "Chennai Super Kings",
    teamId: "csk",
    matches: 9,
    wins: 2,
    losses: 7,
    ties: 0,
    noResult: 0,
    points: 4,
    nrr: -1.302,
  },
];
